name: flutter_face_pile
description: A group of overlapping round avatars are called face piles.
issue_tracker: https://github.com/cmedamine/flutter-face-pile/issues
repository: https://github.com/cmedamine/flutter-face-pile
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
